title = "Syntax Sugar"
languageCode = "en-us"
baseurl = "http://syntaxsugar.de/"
pluralizeListTitles = false
PygmentsCodeFences = true
pygmentsuseclasses = true
ignoreFiles = [ "/css/.sass-cache" ]

[Taxonomies]
tag = "tags"

[params]
email = "sebastian@syntaxsugar.de"